CREATE TABLE department(
	id INT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(255) UNIQUE NOT NULL ,
	login VARCHAR(255) UNIQUE NOT NULL ,
	password VARCHAR(255) NOT NULL,
	enabled TINYINT NOT NULL DEFAULT 1,
	
	PRIMARY KEY(id)
) CHARACTER SET = utf8 COLLATE utf8_unicode_ci;