INSERT INTO subject (name, subject_type) VALUES('Mathematical analysis', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Mathematical analysis', 'practice');
INSERT INTO subject (name, subject_type) VALUES('Information Technology', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Information Technology', 'practice');
INSERT INTO subject (name, subject_type) VALUES('Geometry', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Geometry', 'practice');
INSERT INTO subject (name, subject_type) VALUES('A culture of speech', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Foreign language', 'practice');
INSERT INTO subject (name, subject_type) VALUES('Foreign language', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Physical Culture', 'practice');
INSERT INTO subject (name, subject_type) VALUES('Mathematical logic', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Mathematical logic', 'practice');
INSERT INTO subject (name, subject_type) VALUES('Differential equations', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Differential equations', 'practice');
INSERT INTO subject (name, subject_type) VALUES('Discrete Math', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Discrete Math', 'practice');
INSERT INTO subject (name, subject_type) VALUES('Economics', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Economics', 'practice');
INSERT INTO subject (name, subject_type) VALUES('Social science', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Math modeling', 'lecture');
INSERT INTO subject (name, subject_type) VALUES('Math modeling', 'practice');