INSERT INTO subject (name, subject_type) VALUES('Mathematical analysis', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Mathematical analysis', 'PRACTICE');
INSERT INTO subject (name, subject_type) VALUES('Information Technology', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Information Technology', 'PRACTICE');
INSERT INTO subject (name, subject_type) VALUES('Geometry', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Geometry', 'PRACTICE');
INSERT INTO subject (name, subject_type) VALUES('A culture of speech', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Foreign language', 'PRACTICE');
INSERT INTO subject (name, subject_type) VALUES('Foreign language', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Physical Culture', 'PRACTICE');
INSERT INTO subject (name, subject_type) VALUES('Mathematical logic', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Mathematical logic', 'PRACTICE');
INSERT INTO subject (name, subject_type) VALUES('Differential equations', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Differential equations', 'PRACTICE');
INSERT INTO subject (name, subject_type) VALUES('Discrete Math', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Discrete Math', 'PRACTICE');
INSERT INTO subject (name, subject_type) VALUES('Economics', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Economics', 'PRACTICE');
INSERT INTO subject (name, subject_type) VALUES('Social science', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Math modeling', 'LECTURE');
INSERT INTO subject (name, subject_type) VALUES('Math modeling', 'PRACTICE');