CREATE TABLE students(
	id INT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	family_name  VARCHAR(255) NOT NULL,
	id_group INT UNSIGNED NOT NULL,
	id_user_info INT UNSIGNED NOT NULL,
	
	PRIMARY KEY (id),
	FOREIGN KEY (id_group) REFERENCES groups(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_user_info) REFERENCES user_info (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT unique_student UNIQUE(name, family_name)
) CHARACTER SET = utf8 COLLATE utf8_unicode_ci;