CREATE TABLE teachers(
	id INT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	family_name  VARCHAR(255) NOT NULL,
	id_subject INT  UNSIGNED NOT NULL,
	id_department INT UNSIGNED NOT NULL,
	id_user_info INT UNSIGNED NOT NULL,
	
	PRIMARY KEY (id),
	CONSTRAINT unique_teacher UNIQUE(name, family_name),
	FOREIGN KEY (id_subject) REFERENCES subject (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_department) REFERENCES department (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_user_info) REFERENCES user_info (id) ON DELETE CASCADE ON UPDATE CASCADE
) CHARACTER SET = utf8 COLLATE utf8_unicode_ci;